#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH --partition=shared
#SBATCH --nodes 1
#SBATCH --export=ALL
#SBATCH --account=cit197
#SBATCH --mem=12G
#SBATCH --ntasks-per-node=1

source /home/jskinner1/miniconda3/bin/activate

if ! command -v conda &> /dev/null; then
    echo "conda not found, initializing conda"
    source /home/jskinner1/miniconda3/etc/profile.d/conda.sh
    conda init
fi

conda activate d3
python3 Download_AVISO_L3.py