#!/bin/bash
#SBATCH --job-name=swot_balanced_extraction_array
#SBATCH --time=5:00:00
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G
#SBATCH --account=cit197
#SBATCH --export=ALL
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --error=logs/%x_%A_%a.err
#SBATCH --array=0-15   # 16 passes

# -------- configure passes --------
PASS_LIST=(507 535 563 548 492 285 257 229 201 298 270 242 313 326 214 576)

PASS_NUM=${PASS_LIST[$SLURM_ARRAY_TASK_ID]}
echo "[INFO] idx=${SLURM_ARRAY_TASK_ID} -> PASS=${PASS_NUM}"

# thread hygiene
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_MAX_THREADS=4

# env
source /home/jskinner1/miniconda3/etc/profile.d/conda.sh
conda activate d3

# run
srun -c ${SLURM_CPUS_PER_TASK} python3 Interpolate_the_gap.py --pass "${PASS_NUM}"
