#!/bin/bash
#SBATCH -t 48:00:00

#SBATCH --partition=compute
#SBATCH --nodes 1
#SBATCH --export=ALL
#SBATCH --account=cit197
#SBATCH --mem=128G
#SBATCH --ntasks-per-node=2

module load slurm
source /home/jskinner1/miniconda3/bin/activate

# Initialize conda if not already initialized
if ! command -v conda &> /dev/null; then
    echo "conda not found, initializing conda"
    source /home/jskinner1/miniconda3/etc/profile.d/conda.sh
    conda init
fi

conda activate d3

python3 Interpolate_the_gap.py